export const FETCH_REVIEWDATA_REQUEST = 'FETCH_REVIEWDATA_REQUEST';
export const FETCH_REVIEWDATA_SUCCESS = 'FETCH_REVIEWDATA_SUCCESS';
export const FETCH_REVIEWDATA_FAILURE = 'FETCH_REVIEWDATA_FAILURE';